// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFj3lCFq3eL95XVsrLxox8fiov5f4bajo',
    appId: '1:248462708365:android:4de82e8e07181962a6dcc4',
    messagingSenderId: '248462708365',
    projectId: 'fir-popapp-6778d',
    databaseURL: 'https://fir-popapp-6778d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-popapp-6778d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTSOV0MtcCN-l-JzayEacHqVLCITilR6s',
    appId: '1:248462708365:ios:c40eaf2c0a5b81f1a6dcc4',
    messagingSenderId: '248462708365',
    projectId: 'fir-popapp-6778d',
    databaseURL: 'https://fir-popapp-6778d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-popapp-6778d.firebasestorage.app',
    iosBundleId: 'com.example.popapp',
  );
}
